Time t;
    t.inputTime();
    cout << "--------------------------------\n";
    cout << "Initial Time         : ";
    t.displayTime();
    ++t;
    cout << "--------------------------------\n";
    cout << "After increment 1 minute : ";
    t.displayTime();
    cout << "=================================\n";
